import feedPic from "../src/assets/ceo-avatar.svg";



const  feedbackData = [
    {
        id: 1,
        rating: "5.0",
        name: "Ashton Cox",
        comment: "Thank you elearing for the website develope for our organisation. we love your company and we wont stop patronizing you",
        avatar: feedPic,
        company: "AAUA",

    },
    {
        id: 2,
        rating: "5.0",
        name: "Ashton Cox",
        comment: "Thank you elearing for the website develope for our organisation. we love your company and we wont stop patronizing you",
        avatar: feedPic,
        company: "AAUA",

    },
    {
        id: 3,
        rating: "5.0",
        name: "Ashton Cox",
        comment: "Thank you elearing for the website develope for our organisation. we love your company and we wont stop patronizing you",
        avatar: feedPic,
        company: "AAUA",

    },
    {
        id: 4,
        rating: "5.0",
        name: "Ashton Cox",
        comment: "Thank you elearing for the website develope for our organisation. we love your company and we wont stop patronizing you",
        avatar: feedPic,
        company: "AAUA",

    }
]

export default feedbackData